//! `ter new`: a new project for a board, generated by the installed
//! xiao-generate.

use std::ffi::OsString;
use std::path::PathBuf;
use std::process::{Command, Stdio};

use serde::Serialize;
use ter_gen::new::{GENERATOR, Listing, NewArgs, listing_args};

use crate::output::{CliError, print_json};

#[derive(Serialize)]
struct Generated {
    board: String,
    hal: Option<String>,
    r#async: bool,
    name: String,
    dir: PathBuf,
    /// The xiao-generate command ter ran.
    command: String,
}

fn generator() -> Result<PathBuf, CliError> {
    ter_gen::install::find_program(GENERATOR).ok_or_else(|| {
        CliError::new(
            "not_installed",
            format!(
                "{GENERATOR} is not installed, and ter new runs it. Install it with `ter install {GENERATOR}`."
            ),
        )
    })
}

/// With `--json` xiao-generate's own output goes to stderr, so stdout
/// stays one JSON document.
fn run_generator(args: &[OsString], json: bool) -> Result<(), CliError> {
    let mut command = Command::new(generator()?);
    command.args(args).stdin(Stdio::null());
    if json {
        command.stdout(std::io::stderr());
    }
    let status = command
        .status()
        .map_err(|e| CliError::new("generate_failed", format!("Could not run {GENERATOR}: {e}")))?;
    if status.success() {
        Ok(())
    } else {
        Err(CliError::new(
            "generate_failed",
            format!("{GENERATOR} could not generate the project ({status}); its message is above."),
        ))
    }
}

pub fn new(args: NewArgs, json: bool) -> Result<(), CliError> {
    let gen_args = args.generator_args();
    run_generator(&gen_args, json)?;
    if json {
        let dir = args.out_dir();
        print_json(&Generated {
            board: args.board,
            hal: args.hal,
            r#async: args.r#async,
            name: args.name,
            dir: std::path::absolute(&dir).unwrap_or(dir),
            command: std::iter::once(GENERATOR.into())
                .chain(gen_args.iter().map(|a| a.to_string_lossy().into_owned()))
                .collect::<Vec<String>>()
                .join(" "),
        });
    }
    Ok(())
}

/// The boards, HALs or templates xiao-generate supports, as it prints
/// them. With `--json`, its text under `listing`.
pub fn list(listing: Listing, board: Option<&str>, json: bool) -> Result<(), CliError> {
    let args = listing_args(listing, board);
    if !json {
        return run_generator(&args, false);
    }
    let out = Command::new(generator()?)
        .args(&args)
        .stdin(Stdio::null())
        .output()
        .map_err(|e| CliError::new("generate_failed", format!("Could not run {GENERATOR}: {e}")))?;
    if !out.status.success() {
        return Err(CliError::new(
            "generate_failed",
            String::from_utf8_lossy(&out.stderr).trim().to_string(),
        ));
    }
    print_json(&serde_json::json!({ "listing": String::from_utf8_lossy(&out.stdout) }));
    Ok(())
}
