//! `ter new`: a new project for a board, generated by xiao-generate.
//!
//! ter does not generate projects itself. It runs the installed
//! `xiao-generate --headless`, so `ter new` supports exactly the boards,
//! HALs and templates xiao-generate does. ter's own flags are mapped onto
//! xiao-generate's; everything after `--` is passed through as is.

use std::ffi::OsString;
use std::path::PathBuf;

/// The generator `ter new` runs.
pub const GENERATOR: &str = "xiao-generate";

/// What `ter new` was asked for.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct NewArgs {
    /// The board, as xiao-generate names it (`xiao-esp32c3`).
    pub board: String,
    /// The HAL stack (`esp-hal`, `esp-idf`, `embassy-rp`); the board's
    /// default when absent.
    pub hal: Option<String>,
    /// Async: the embassy framework instead of blocking code.
    pub r#async: bool,
    pub name: String,
    /// Where the project goes; `./<name>` when absent.
    pub out: Option<PathBuf>,
    pub template: Option<String>,
    pub logging: Option<String>,
    pub flashing: Option<String>,
    /// Let xiao-generate install what it needs (esp-generate, targets)
    /// without asking.
    pub yes: bool,
    /// Never let xiao-generate install anything.
    pub no_install: bool,
    /// Passed through to xiao-generate unchanged.
    pub extra: Vec<OsString>,
}

impl NewArgs {
    /// The folder the project is written to.
    pub fn out_dir(&self) -> PathBuf {
        self.out
            .clone()
            .unwrap_or_else(|| PathBuf::from(&self.name))
    }

    /// xiao-generate's arguments for this request.
    pub fn generator_args(&self) -> Vec<OsString> {
        let mut args: Vec<OsString> = Vec::new();
        let mut flag = |name: &str, value: Option<&str>| {
            args.push(format!("--{name}").into());
            if let Some(v) = value {
                args.push(v.into());
            }
        };
        flag("headless", None);
        flag("chip", Some(&self.board));
        if let Some(hal) = &self.hal {
            flag("stack", Some(hal));
        }
        if self.r#async {
            flag("framework", Some("embassy"));
        }
        flag("name", Some(&self.name));
        if let Some(t) = &self.template {
            flag("template", Some(t));
        }
        if let Some(l) = &self.logging {
            flag("logging", Some(l));
        }
        if let Some(f) = &self.flashing {
            flag("flashing", Some(f));
        }
        if self.yes {
            flag("yes", None);
        }
        if self.no_install {
            flag("no-install", None);
        }
        args.push("--out".into());
        args.push(self.out_dir().into_os_string());
        args.extend(self.extra.iter().cloned());
        args
    }
}

/// The list xiao-generate prints for `ter new --list-boards` and friends.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Listing {
    Boards,
    Hals,
    Templates,
}

/// xiao-generate's arguments for a listing, for one board or all.
pub fn listing_args(listing: Listing, board: Option<&str>) -> Vec<OsString> {
    let mut args: Vec<OsString> = vec![
        match listing {
            Listing::Boards => "--list-chips",
            Listing::Hals => "--list-stacks",
            Listing::Templates => "--list-templates",
        }
        .into(),
    ];
    if let Some(b) = board {
        args.push("--chip".into());
        args.push(b.into());
    }
    args
}

#[cfg(test)]
mod tests {
    use super::*;

    fn strings(args: Vec<OsString>) -> Vec<String> {
        args.into_iter().map(|a| a.into_string().unwrap()).collect()
    }

    #[test]
    fn the_board_alone_is_headless_with_its_name_and_folder() {
        let args = NewArgs {
            board: "xiao-esp32c3".into(),
            name: "blinky".into(),
            ..Default::default()
        };
        assert_eq!(
            strings(args.generator_args()),
            [
                "--headless",
                "--chip",
                "xiao-esp32c3",
                "--name",
                "blinky",
                "--out",
                "blinky"
            ]
        );
    }

    #[test]
    fn ters_flags_map_onto_xiao_generates_and_extras_pass_through() {
        let args = NewArgs {
            board: "xiao-rp2040".into(),
            hal: Some("embassy-rp".into()),
            r#async: true,
            name: "exercise".into(),
            out: Some("/tmp/x/exercise".into()),
            template: Some("base-blink".into()),
            logging: Some("defmt".into()),
            flashing: Some("probe-rs".into()),
            no_install: true,
            extra: vec!["--editor".into(), "helix".into()],
            ..Default::default()
        };
        assert_eq!(
            strings(args.generator_args()),
            [
                "--headless",
                "--chip",
                "xiao-rp2040",
                "--stack",
                "embassy-rp",
                "--framework",
                "embassy",
                "--name",
                "exercise",
                "--template",
                "base-blink",
                "--logging",
                "defmt",
                "--flashing",
                "probe-rs",
                "--no-install",
                "--out",
                "/tmp/x/exercise",
                "--editor",
                "helix",
            ]
        );
    }

    #[test]
    fn listings_use_xiao_generates_list_flags() {
        assert_eq!(
            strings(listing_args(Listing::Boards, None)),
            ["--list-chips"]
        );
        assert_eq!(
            strings(listing_args(Listing::Hals, Some("xiao-esp32c3"))),
            ["--list-stacks", "--chip", "xiao-esp32c3"]
        );
        assert_eq!(
            strings(listing_args(Listing::Templates, None)),
            ["--list-templates"]
        );
    }
}
