[package]
name = "ter-flash"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serialport = "4.10"

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
